//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.8.2.0 (NJsonSchema v10.2.1.0 (Newtonsoft.Json v12.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

using System.Linq;

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."

namespace PolicyExampleAPI
{
    using System = global::System;
    
    [System.CodeDom.Compiler.GeneratedCode("NSwag", "13.8.2.0 (NJsonSchema v10.2.1.0 (Newtonsoft.Json v12.0.0.0))")]
    public interface IPolicyController
    {
        /// <summary>Get policies</summary>
        /// <returns>OK</returns>
        System.Threading.Tasks.Task<Response<System.Collections.Generic.ICollection<PolicyState>>> PolicyGetAsync();
    
        /// <summary>Create policy</summary>
        /// <returns>OK</returns>
        System.Threading.Tasks.Task<Response<string>> PolicyPostAsync();
    
        /// <summary>Get policy details</summary>
        /// <param name="policyId">id of the policy for the operation</param>
        /// <returns>OK</returns>
        System.Threading.Tasks.Task<Response<PolicyState>> PolicyGetAsync(string policyId);
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NSwag", "13.8.2.0 (NJsonSchema v10.2.1.0 (Newtonsoft.Json v12.0.0.0))")]
    public partial class PolicyController : Microsoft.AspNetCore.Mvc.Controller
    {
        private IPolicyController _implementation;
    
        public PolicyController(IPolicyController implementation)
        {
            _implementation = implementation;
        }
    
        /// <summary>Get policies</summary>
        /// <returns>OK</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("policy")]
        public async System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.IActionResult> PolicyGet()
        {
            var result = await _implementation.PolicyGetAsync().ConfigureAwait(false);
    
            var status = result.StatusCode;
            Microsoft.AspNetCore.Mvc.ObjectResult response = new Microsoft.AspNetCore.Mvc.ObjectResult(result.Result) { StatusCode = status };
    
            foreach (var header in result.Headers)
                Request.HttpContext.Response.Headers.Add(header.Key, new Microsoft.Extensions.Primitives.StringValues(header.Value.ToArray()));
    
            return response;
        }
    
        /// <summary>Create policy</summary>
        /// <returns>OK</returns>
        [Microsoft.AspNetCore.Mvc.HttpPost, Microsoft.AspNetCore.Mvc.Route("policy")]
        public async System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.IActionResult> PolicyPost()
        {
            var result = await _implementation.PolicyPostAsync().ConfigureAwait(false);
    
            var status = result.StatusCode;
            Microsoft.AspNetCore.Mvc.ObjectResult response = new Microsoft.AspNetCore.Mvc.ObjectResult(result.Result) { StatusCode = status };
    
            foreach (var header in result.Headers)
                Request.HttpContext.Response.Headers.Add(header.Key, new Microsoft.Extensions.Primitives.StringValues(header.Value.ToArray()));
    
            return response;
        }
    
        /// <summary>Get policy details</summary>
        /// <param name="policyId">id of the policy for the operation</param>
        /// <returns>OK</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("policy/{policyId}")]
        public async System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.IActionResult> PolicyGet(string policyId)
        {
            var result = await _implementation.PolicyGetAsync(policyId).ConfigureAwait(false);
    
            var status = result.StatusCode;
            Microsoft.AspNetCore.Mvc.ObjectResult response = new Microsoft.AspNetCore.Mvc.ObjectResult(result.Result) { StatusCode = status };
    
            foreach (var header in result.Headers)
                Request.HttpContext.Response.Headers.Add(header.Key, new Microsoft.Extensions.Primitives.StringValues(header.Value.ToArray()));
    
            return response;
        }
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NSwag", "13.8.2.0 (NJsonSchema v10.2.1.0 (Newtonsoft.Json v12.0.0.0))")]
    public interface IIssuanceController
    {
        /// <summary>Get issuance requests</summary>
        /// <returns>OK</returns>
        System.Threading.Tasks.Task<Response<System.Collections.Generic.ICollection<IssuanceWithStatus>>> IssuanceGetAsync(string policyId);
    
        /// <summary>Create issuance request</summary>
        /// <returns>OK</returns>
        System.Threading.Tasks.Task<Response<RequestStatus>> IssuancePostAsync(IssuanceRequest body, string policyId);
    
        /// <summary>Get issuance request details</summary>
        /// <returns>OK</returns>
        System.Threading.Tasks.Task<Response<IssuanceWithStatus>> IssuanceGetAsync(string policyId, string issuanceId);
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NSwag", "13.8.2.0 (NJsonSchema v10.2.1.0 (Newtonsoft.Json v12.0.0.0))")]
    public partial class IssuanceController : Microsoft.AspNetCore.Mvc.Controller
    {
        private IIssuanceController _implementation;
    
        public IssuanceController(IIssuanceController implementation)
        {
            _implementation = implementation;
        }
    
        /// <summary>Get issuance requests</summary>
        /// <returns>OK</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("policy/{policyId}/issuance")]
        public async System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.IActionResult> IssuanceGet(string policyId)
        {
            var result = await _implementation.IssuanceGetAsync(policyId).ConfigureAwait(false);
    
            var status = result.StatusCode;
            Microsoft.AspNetCore.Mvc.ObjectResult response = new Microsoft.AspNetCore.Mvc.ObjectResult(result.Result) { StatusCode = status };
    
            foreach (var header in result.Headers)
                Request.HttpContext.Response.Headers.Add(header.Key, new Microsoft.Extensions.Primitives.StringValues(header.Value.ToArray()));
    
            return response;
        }
    
        /// <summary>Create issuance request</summary>
        /// <returns>OK</returns>
        [Microsoft.AspNetCore.Mvc.HttpPost, Microsoft.AspNetCore.Mvc.Route("policy/{policyId}/issuance")]
        public async System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.IActionResult> IssuancePost([Microsoft.AspNetCore.Mvc.FromBody] IssuanceRequest body, string policyId)
        {
            var result = await _implementation.IssuancePostAsync(body, policyId).ConfigureAwait(false);
    
            var status = result.StatusCode;
            Microsoft.AspNetCore.Mvc.ObjectResult response = new Microsoft.AspNetCore.Mvc.ObjectResult(result.Result) { StatusCode = status };
    
            foreach (var header in result.Headers)
                Request.HttpContext.Response.Headers.Add(header.Key, new Microsoft.Extensions.Primitives.StringValues(header.Value.ToArray()));
    
            return response;
        }
    
        /// <summary>Get issuance request details</summary>
        /// <returns>OK</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("policy/{policyId}/issuance/{issuanceId}")]
        public async System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.IActionResult> IssuanceGet(string policyId, string issuanceId)
        {
            var result = await _implementation.IssuanceGetAsync(policyId, issuanceId).ConfigureAwait(false);
    
            var status = result.StatusCode;
            Microsoft.AspNetCore.Mvc.ObjectResult response = new Microsoft.AspNetCore.Mvc.ObjectResult(result.Result) { StatusCode = status };
    
            foreach (var header in result.Headers)
                Request.HttpContext.Response.Headers.Add(header.Key, new Microsoft.Extensions.Primitives.StringValues(header.Value.ToArray()));
    
            return response;
        }
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NSwag", "13.8.2.0 (NJsonSchema v10.2.1.0 (Newtonsoft.Json v12.0.0.0))")]
    public interface IConfigurationController
    {
        /// <summary>Get policy configurations</summary>
        /// <returns>OK</returns>
        System.Threading.Tasks.Task<Response<System.Collections.Generic.ICollection<ConfigurationWithStatus>>> ConfigurationsGetAsync(string policyId);
    
        /// <summary>Create policy configuration</summary>
        /// <returns>OK</returns>
        System.Threading.Tasks.Task<Response<RequestStatus>> ConfigurationsPostAsync(Configuration body, string policyId);
    
        /// <summary>Get policy configuration details</summary>
        /// <returns>OK</returns>
        System.Threading.Tasks.Task<Response<ConfigurationWithStatus>> ConfigurationsGetAsync(string policyId, string configurationId);
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NSwag", "13.8.2.0 (NJsonSchema v10.2.1.0 (Newtonsoft.Json v12.0.0.0))")]
    public partial class ConfigurationController : Microsoft.AspNetCore.Mvc.Controller
    {
        private IConfigurationController _implementation;
    
        public ConfigurationController(IConfigurationController implementation)
        {
            _implementation = implementation;
        }
    
        /// <summary>Get policy configurations</summary>
        /// <returns>OK</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("policy/{policyId}/configurations")]
        public async System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.IActionResult> ConfigurationsGet(string policyId)
        {
            var result = await _implementation.ConfigurationsGetAsync(policyId).ConfigureAwait(false);
    
            var status = result.StatusCode;
            Microsoft.AspNetCore.Mvc.ObjectResult response = new Microsoft.AspNetCore.Mvc.ObjectResult(result.Result) { StatusCode = status };
    
            foreach (var header in result.Headers)
                Request.HttpContext.Response.Headers.Add(header.Key, new Microsoft.Extensions.Primitives.StringValues(header.Value.ToArray()));
    
            return response;
        }
    
        /// <summary>Create policy configuration</summary>
        /// <returns>OK</returns>
        [Microsoft.AspNetCore.Mvc.HttpPost, Microsoft.AspNetCore.Mvc.Route("policy/{policyId}/configurations")]
        public async System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.IActionResult> ConfigurationsPost([Microsoft.AspNetCore.Mvc.FromBody] Configuration body, string policyId)
        {
            var result = await _implementation.ConfigurationsPostAsync(body, policyId).ConfigureAwait(false);
    
            var status = result.StatusCode;
            Microsoft.AspNetCore.Mvc.ObjectResult response = new Microsoft.AspNetCore.Mvc.ObjectResult(result.Result) { StatusCode = status };
    
            foreach (var header in result.Headers)
                Request.HttpContext.Response.Headers.Add(header.Key, new Microsoft.Extensions.Primitives.StringValues(header.Value.ToArray()));
    
            return response;
        }
    
        /// <summary>Get policy configuration details</summary>
        /// <returns>OK</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("policy/{policyId}/configurations/{configurationId}")]
        public async System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.IActionResult> ConfigurationsGet(string policyId, string configurationId)
        {
            var result = await _implementation.ConfigurationsGetAsync(policyId, configurationId).ConfigureAwait(false);
    
            var status = result.StatusCode;
            Microsoft.AspNetCore.Mvc.ObjectResult response = new Microsoft.AspNetCore.Mvc.ObjectResult(result.Result) { StatusCode = status };
    
            foreach (var header in result.Headers)
                Request.HttpContext.Response.Headers.Add(header.Key, new Microsoft.Extensions.Primitives.StringValues(header.Value.ToArray()));
    
            return response;
        }
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NSwag", "13.8.2.0 (NJsonSchema v10.2.1.0 (Newtonsoft.Json v12.0.0.0))")]
    public interface IBusinessTimeController
    {
        /// <summary>Get policy business time</summary>
        /// <returns>OK</returns>
        System.Threading.Tasks.Task<Response<System.DateTimeOffset>> BusinesstimeGetAsync(string policyId);
    
        /// <summary>Override policy business time</summary>
        /// <returns>Accepted</returns>
        System.Threading.Tasks.Task<Response> BusinesstimePostAsync(System.DateTimeOffset? body, string policyId);
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NSwag", "13.8.2.0 (NJsonSchema v10.2.1.0 (Newtonsoft.Json v12.0.0.0))")]
    public partial class BusinessTimeController : Microsoft.AspNetCore.Mvc.Controller
    {
        private IBusinessTimeController _implementation;
    
        public BusinessTimeController(IBusinessTimeController implementation)
        {
            _implementation = implementation;
        }
    
        /// <summary>Get policy business time</summary>
        /// <returns>OK</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("policy/{policyId}/businesstime")]
        public async System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.IActionResult> BusinesstimeGet(string policyId)
        {
            var result = await _implementation.BusinesstimeGetAsync(policyId).ConfigureAwait(false);
    
            var status = result.StatusCode;
            Microsoft.AspNetCore.Mvc.ObjectResult response = new Microsoft.AspNetCore.Mvc.ObjectResult(result.Result) { StatusCode = status };
    
            foreach (var header in result.Headers)
                Request.HttpContext.Response.Headers.Add(header.Key, new Microsoft.Extensions.Primitives.StringValues(header.Value.ToArray()));
    
            return response;
        }
    
        /// <summary>Override policy business time</summary>
        /// <returns>Accepted</returns>
        [Microsoft.AspNetCore.Mvc.HttpPost, Microsoft.AspNetCore.Mvc.Route("policy/{policyId}/businesstime")]
        public async System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.IActionResult> BusinesstimePost([Microsoft.AspNetCore.Mvc.FromBody] System.DateTimeOffset? body, string policyId)
        {
            var result = await _implementation.BusinesstimePostAsync(body, policyId).ConfigureAwait(false);
    
            var status = result.StatusCode;
            Microsoft.AspNetCore.Mvc.ObjectResult response = new Microsoft.AspNetCore.Mvc.ObjectResult(result) { StatusCode = status };
    
            foreach (var header in result.Headers)
                Request.HttpContext.Response.Headers.Add(header.Key, new Microsoft.Extensions.Primitives.StringValues(header.Value.ToArray()));
    
            return response;
        }
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NSwag", "13.8.2.0 (NJsonSchema v10.2.1.0 (Newtonsoft.Json v12.0.0.0))")]
    public interface IClaimsController
    {
        /// <summary>Get policy claims</summary>
        /// <returns>OK</returns>
        System.Threading.Tasks.Task<Response<System.Collections.Generic.ICollection<ClaimWithStatus>>> ClaimGetAsync(string policyId);
    
        /// <summary>Submit policy claim</summary>
        /// <returns>OK</returns>
        System.Threading.Tasks.Task<Response> ClaimPostAsync(Claim body, string policyId);
    
        /// <summary>Get policy claim details</summary>
        /// <returns>OK</returns>
        System.Threading.Tasks.Task<Response<ClaimWithStatus>> ClaimGetAsync(string policyId, string claimId);
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NSwag", "13.8.2.0 (NJsonSchema v10.2.1.0 (Newtonsoft.Json v12.0.0.0))")]
    public partial class ClaimsController : Microsoft.AspNetCore.Mvc.Controller
    {
        private IClaimsController _implementation;
    
        public ClaimsController(IClaimsController implementation)
        {
            _implementation = implementation;
        }
    
        /// <summary>Get policy claims</summary>
        /// <returns>OK</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("policy/{policyId}/claim")]
        public async System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.IActionResult> ClaimGet(string policyId)
        {
            var result = await _implementation.ClaimGetAsync(policyId).ConfigureAwait(false);
    
            var status = result.StatusCode;
            Microsoft.AspNetCore.Mvc.ObjectResult response = new Microsoft.AspNetCore.Mvc.ObjectResult(result.Result) { StatusCode = status };
    
            foreach (var header in result.Headers)
                Request.HttpContext.Response.Headers.Add(header.Key, new Microsoft.Extensions.Primitives.StringValues(header.Value.ToArray()));
    
            return response;
        }
    
        /// <summary>Submit policy claim</summary>
        /// <returns>OK</returns>
        [Microsoft.AspNetCore.Mvc.HttpPost, Microsoft.AspNetCore.Mvc.Route("policy/{policyId}/claim")]
        public async System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.IActionResult> ClaimPost([Microsoft.AspNetCore.Mvc.FromBody] Claim body, string policyId)
        {
            var result = await _implementation.ClaimPostAsync(body, policyId).ConfigureAwait(false);
    
            var status = result.StatusCode;
            Microsoft.AspNetCore.Mvc.ObjectResult response = new Microsoft.AspNetCore.Mvc.ObjectResult(result) { StatusCode = status };
    
            foreach (var header in result.Headers)
                Request.HttpContext.Response.Headers.Add(header.Key, new Microsoft.Extensions.Primitives.StringValues(header.Value.ToArray()));
    
            return response;
        }
    
        /// <summary>Get policy claim details</summary>
        /// <returns>OK</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("policy/{policyId}/claim/{claimId}")]
        public async System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.IActionResult> ClaimGet(string policyId, string claimId)
        {
            var result = await _implementation.ClaimGetAsync(policyId, claimId).ConfigureAwait(false);
    
            var status = result.StatusCode;
            Microsoft.AspNetCore.Mvc.ObjectResult response = new Microsoft.AspNetCore.Mvc.ObjectResult(result.Result) { StatusCode = status };
    
            foreach (var header in result.Headers)
                Request.HttpContext.Response.Headers.Add(header.Key, new Microsoft.Extensions.Primitives.StringValues(header.Value.ToArray()));
    
            return response;
        }
    
    }

    /// <summary>Status of a request sent  </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.2.1.0 (Newtonsoft.Json v12.0.0.0)")]
    public enum RequestState
    {
        [System.Runtime.Serialization.EnumMember(Value = @"pending")]
        Pending = 0,
    
        [System.Runtime.Serialization.EnumMember(Value = @"received")]
        Received = 1,
    
        [System.Runtime.Serialization.EnumMember(Value = @"processing")]
        Processing = 2,
    
        [System.Runtime.Serialization.EnumMember(Value = @"completed")]
        Completed = 3,
    
        [System.Runtime.Serialization.EnumMember(Value = @"rejected")]
        Rejected = 4,
    
    }
    
    /// <summary>State of an insurance policy</summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.2.1.0 (Newtonsoft.Json v12.0.0.0)")]
    public partial class PolicyState 
    {
        [Newtonsoft.Json.JsonProperty("issued", Required = Newtonsoft.Json.Required.Always)]
        public bool Issued { get; set; }
    
        [Newtonsoft.Json.JsonProperty("duration", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Range(0D, double.MaxValue)]
        public long Duration { get; set; }
    
        [Newtonsoft.Json.JsonProperty("issueDate", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.StringLength(int.MaxValue, MinimumLength = 1)]
        public System.DateTimeOffset IssueDate { get; set; }
    
        [Newtonsoft.Json.JsonProperty("expiryDate", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.DateTimeOffset? ExpiryDate { get; set; }
    
        [Newtonsoft.Json.JsonProperty("isExpired", Required = Newtonsoft.Json.Required.Always)]
        public bool IsExpired { get; set; }
    
        [Newtonsoft.Json.JsonProperty("amount", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Range(1, int.MaxValue)]
        public int Amount { get; set; }
    
        [Newtonsoft.Json.JsonProperty("businessTime", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.StringLength(int.MaxValue, MinimumLength = 1)]
        public System.DateTimeOffset BusinessTime { get; set; }
    
        [Newtonsoft.Json.JsonProperty("id", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Id { get; set; }
    
        private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();
    
        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties; }
            set { _additionalProperties = value; }
        }
    
    
    }
    
    /// <summary>A request to issue a policy at given time. </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.2.1.0 (Newtonsoft.Json v12.0.0.0)")]
    public partial class IssuanceRequest 
    {
        [Newtonsoft.Json.JsonProperty("policyId", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string PolicyId { get; set; }
    
        /// <summary>Time when policy should be issued. Can be null for immediate issue or a moment in the future
        /// </summary>
        [Newtonsoft.Json.JsonProperty("issueTime", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.DateTimeOffset? IssueTime { get; set; }
    
        private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();
    
        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties; }
            set { _additionalProperties = value; }
        }
    
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.2.1.0 (Newtonsoft.Json v12.0.0.0)")]
    public partial class RequestStatus 
    {
        [Newtonsoft.Json.JsonProperty("id", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Id { get; set; }
    
        [Newtonsoft.Json.JsonProperty("status", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public RequestState Status { get; set; }
    
        [Newtonsoft.Json.JsonProperty("error", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Error { get; set; }
    
        private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();
    
        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties; }
            set { _additionalProperties = value; }
        }
    
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.2.1.0 (Newtonsoft.Json v12.0.0.0)")]
    public partial class Configuration 
    {
        [Newtonsoft.Json.JsonProperty("requestId", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string RequestId { get; set; }
    
        [Newtonsoft.Json.JsonProperty("amount", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Range(1, int.MaxValue)]
        public int Amount { get; set; }
    
        [Newtonsoft.Json.JsonProperty("duration", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Range(0D, double.MaxValue)]
        public long Duration { get; set; }
    
        [Newtonsoft.Json.JsonProperty("policyId", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string PolicyId { get; set; }
    
        private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();
    
        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties; }
            set { _additionalProperties = value; }
        }
    
    
    }
    
    /// <summary>A claim filled towards a policy</summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.2.1.0 (Newtonsoft.Json v12.0.0.0)")]
    public partial class Claim 
    {
        [Newtonsoft.Json.JsonProperty("id", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Id { get; set; }
    
        [Newtonsoft.Json.JsonProperty("amount", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Range(0, int.MaxValue)]
        public int Amount { get; set; }
    
        private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();
    
        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties; }
            set { _additionalProperties = value; }
        }
    
    
    }
    
    /// <summary>Issuance request with its status </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.2.1.0 (Newtonsoft.Json v12.0.0.0)")]
    public partial class IssuanceWithStatus 
    {
        [Newtonsoft.Json.JsonProperty("issuance", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public IssuanceRequest Issuance { get; set; }
    
        [Newtonsoft.Json.JsonProperty("status", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public RequestStatus Status { get; set; }
    
        private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();
    
        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties; }
            set { _additionalProperties = value; }
        }
    
    
    }
    
    /// <summary>Configuration request details with its status</summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.2.1.0 (Newtonsoft.Json v12.0.0.0)")]
    public partial class ConfigurationWithStatus 
    {
        [Newtonsoft.Json.JsonProperty("configuration", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public Configuration Configuration { get; set; }
    
        [Newtonsoft.Json.JsonProperty("status", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public RequestStatus Status { get; set; }
    
        private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();
    
        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties; }
            set { _additionalProperties = value; }
        }
    
    
    }
    
    /// <summary>Claim information with its status</summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.2.1.0 (Newtonsoft.Json v12.0.0.0)")]
    public partial class ClaimWithStatus 
    {
        [Newtonsoft.Json.JsonProperty("claim", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public Claim Claim { get; set; }
    
        [Newtonsoft.Json.JsonProperty("status", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public RequestStatus Status { get; set; }
    
        private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();
    
        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties; }
            set { _additionalProperties = value; }
        }
    
    
    }

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "13.8.2.0 (NJsonSchema v10.2.1.0 (Newtonsoft.Json v12.0.0.0))")]
    public partial class Response
    {
        public int StatusCode { get; private set; }

        public System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> Headers { get; private set; }
        
        public Response(int statusCode, System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> headers) 
        {
            StatusCode = statusCode; 
            Headers = headers;
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "13.8.2.0 (NJsonSchema v10.2.1.0 (Newtonsoft.Json v12.0.0.0))")]
    public partial class Response<TResult> : Response
    {
        public TResult Result { get; private set; }
        
        public Response(int statusCode, System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> headers, TResult result) 
            : base(statusCode, headers)
        {
            Result = result;
        }
    }

}

#pragma warning restore 1591
#pragma warning restore 1573
#pragma warning restore  472
#pragma warning restore  114
#pragma warning restore  108